// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/store/contract.go
//
// Generated by this command:
//
//	mockgen -source=./internal/store/contract.go -destination=./internal/store/mock/store_mock.go -package=mock_store
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	models "github.com/Negat1v9/pr-review-service/internal/models"
	store "github.com/Negat1v9/pr-review-service/internal/store"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateManyUsers mocks base method.
func (m *MockUserRepository) CreateManyUsers(ctx context.Context, exec sqlx.ExtContext, teamName string, users []models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManyUsers", ctx, exec, teamName, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateManyUsers indicates an expected call of CreateManyUsers.
func (mr *MockUserRepositoryMockRecorder) CreateManyUsers(ctx, exec, teamName, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManyUsers", reflect.TypeOf((*MockUserRepository)(nil).CreateManyUsers), ctx, exec, teamName, users)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, exec sqlx.ExtContext, teamName string, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, exec, teamName, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, exec, teamName, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, exec, teamName, user)
}

// GetUserReviews mocks base method.
func (m *MockUserRepository) GetUserReviews(ctx context.Context, exec sqlx.ExtContext, userID string) (*models.UserReviews, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, exec, userID)
	ret0, _ := ret[0].(*models.UserReviews)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockUserRepositoryMockRecorder) GetUserReviews(ctx, exec, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockUserRepository)(nil).GetUserReviews), ctx, exec, userID)
}

// UpdateUserStatus mocks base method.
func (m *MockUserRepository) UpdateUserStatus(ctx context.Context, exec sqlx.ExtContext, userID string, isActive bool) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, exec, userID, isActive)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockUserRepositoryMockRecorder) UpdateUserStatus(ctx, exec, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserStatus), ctx, exec, userID, isActive)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamRepository) CreateTeam(ctx context.Context, exec sqlx.ExtContext, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, exec, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamRepositoryMockRecorder) CreateTeam(ctx, exec, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamRepository)(nil).CreateTeam), ctx, exec, teamName)
}

// GetActiveUsersTeamWithException mocks base method.
func (m *MockTeamRepository) GetActiveUsersTeamWithException(ctx context.Context, exec sqlx.ExtContext, userID string, exceptions []string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersTeamWithException", ctx, exec, userID, exceptions, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersTeamWithException indicates an expected call of GetActiveUsersTeamWithException.
func (mr *MockTeamRepositoryMockRecorder) GetActiveUsersTeamWithException(ctx, exec, userID, exceptions, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersTeamWithException", reflect.TypeOf((*MockTeamRepository)(nil).GetActiveUsersTeamWithException), ctx, exec, userID, exceptions, limit)
}

// GetTeamWithMembers mocks base method.
func (m *MockTeamRepository) GetTeamWithMembers(ctx context.Context, exec sqlx.ExtContext, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWithMembers", ctx, exec, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWithMembers indicates an expected call of GetTeamWithMembers.
func (mr *MockTeamRepositoryMockRecorder) GetTeamWithMembers(ctx, exec, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWithMembers", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamWithMembers), ctx, exec, teamName)
}

// GetUsersIDFromUserTeam mocks base method.
func (m *MockTeamRepository) GetUsersIDFromUserTeam(ctx context.Context, exec sqlx.ExtContext, userID string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersIDFromUserTeam", ctx, exec, userID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersIDFromUserTeam indicates an expected call of GetUsersIDFromUserTeam.
func (mr *MockTeamRepositoryMockRecorder) GetUsersIDFromUserTeam(ctx, exec, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersIDFromUserTeam", reflect.TypeOf((*MockTeamRepository)(nil).GetUsersIDFromUserTeam), ctx, exec, userID, limit)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// AssignManyReviewers mocks base method.
func (m *MockPullRequestRepository) AssignManyReviewers(ctx context.Context, exec sqlx.ExtContext, prID string, reviewerIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignManyReviewers", ctx, exec, prID, reviewerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignManyReviewers indicates an expected call of AssignManyReviewers.
func (mr *MockPullRequestRepositoryMockRecorder) AssignManyReviewers(ctx, exec, prID, reviewerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignManyReviewers", reflect.TypeOf((*MockPullRequestRepository)(nil).AssignManyReviewers), ctx, exec, prID, reviewerIDs)
}

// AssignReviewer mocks base method.
func (m *MockPullRequestRepository) AssignReviewer(ctx context.Context, exec sqlx.ExtContext, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewer", ctx, exec, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewer indicates an expected call of AssignReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) AssignReviewer(ctx, exec, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).AssignReviewer), ctx, exec, prID, reviewerID)
}

// CreatePullRequest mocks base method.
func (m *MockPullRequestRepository) CreatePullRequest(ctx context.Context, exec sqlx.ExtContext, pr *models.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, exec, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) CreatePullRequest(ctx, exec, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).CreatePullRequest), ctx, exec, pr)
}

// DeleteAssignedByReviewerID mocks base method.
func (m *MockPullRequestRepository) DeleteAssignedByReviewerID(ctx context.Context, exec sqlx.ExtContext, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssignedByReviewerID", ctx, exec, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAssignedByReviewerID indicates an expected call of DeleteAssignedByReviewerID.
func (mr *MockPullRequestRepositoryMockRecorder) DeleteAssignedByReviewerID(ctx, exec, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssignedByReviewerID", reflect.TypeOf((*MockPullRequestRepository)(nil).DeleteAssignedByReviewerID), ctx, exec, reviewerID)
}

// GetPullRequestByID mocks base method.
func (m *MockPullRequestRepository) GetPullRequestByID(ctx context.Context, exec sqlx.ExtContext, prID string) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, exec, prID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequestByID(ctx, exec, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequestByID), ctx, exec, prID)
}

// GetQuantityPRReviewers mocks base method.
func (m *MockPullRequestRepository) GetQuantityPRReviewers(ctx context.Context, exec sqlx.ExtContext) ([]models.PullRequestQuantityReviewers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuantityPRReviewers", ctx, exec)
	ret0, _ := ret[0].([]models.PullRequestQuantityReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuantityPRReviewers indicates an expected call of GetQuantityPRReviewers.
func (mr *MockPullRequestRepositoryMockRecorder) GetQuantityPRReviewers(ctx, exec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuantityPRReviewers", reflect.TypeOf((*MockPullRequestRepository)(nil).GetQuantityPRReviewers), ctx, exec)
}

// MergePullRequest mocks base method.
func (m *MockPullRequestRepository) MergePullRequest(ctx context.Context, exec sqlx.ExtContext, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, exec, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) MergePullRequest(ctx, exec, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).MergePullRequest), ctx, exec, prID)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DB mocks base method.
func (m *MockStore) DB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockStoreMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockStore)(nil).DB))
}

// DoTx mocks base method.
func (m *MockStore) DoTx(ctx context.Context, fn func(context.Context, sqlx.ExtContext) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoTx indicates an expected call of DoTx.
func (mr *MockStoreMockRecorder) DoTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTx", reflect.TypeOf((*MockStore)(nil).DoTx), ctx, fn)
}

// PRRepo mocks base method.
func (m *MockStore) PRRepo() store.PullRequestRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRRepo")
	ret0, _ := ret[0].(store.PullRequestRepository)
	return ret0
}

// PRRepo indicates an expected call of PRRepo.
func (mr *MockStoreMockRecorder) PRRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRRepo", reflect.TypeOf((*MockStore)(nil).PRRepo))
}

// TeamRepo mocks base method.
func (m *MockStore) TeamRepo() store.TeamRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamRepo")
	ret0, _ := ret[0].(store.TeamRepository)
	return ret0
}

// TeamRepo indicates an expected call of TeamRepo.
func (mr *MockStoreMockRecorder) TeamRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamRepo", reflect.TypeOf((*MockStore)(nil).TeamRepo))
}

// UserRepo mocks base method.
func (m *MockStore) UserRepo() store.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRepo")
	ret0, _ := ret[0].(store.UserRepository)
	return ret0
}

// UserRepo indicates an expected call of UserRepo.
func (mr *MockStoreMockRecorder) UserRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRepo", reflect.TypeOf((*MockStore)(nil).UserRepo))
}
