{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total goroitines",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(pr_control_service_hits_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/users/setIsActive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(pr_control_service_hits_total{path=\"/users/setIsActive\", code=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pr_control_service_hits_total{path=~\"/users/setIsActive\", code=~\"2..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/team/add ",
   "type": "timeseries",
   "description": "total requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pr_control_service_hits_total{path=~\"/team/get\", code=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pr_control_service_hits_total{code=~\"200\", path=~\"/team/get\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}